#!/usr/bin/env python3
"""Regenerates src/ui/logoWordmark.ts: the "arelysig" wordmark as
SVG path outlines (Archivo Bold, width axis 88, letter-spacing -0.035em), so the
wordmark itself ships as outlines, not a webfont. See design/logo/README.md.
(The UI font, a separate use of the same family, is a real webfont built by
scripts/make-ui-font.py — design note 25, #58.)

Usage:  python3 scripts/make-wordmark.py ['path/to/Archivo[wdth,wght].ttf']
        Defaults to the vendored design/fonts/Archivo[wdth,wght].ttf.
Needs:  pip install fonttools uharfbuzz   (Archivo is OFL-1.1, from
        https://github.com/Omnibus-Type/Archivo)
"""
import os
import sys
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
import uharfbuzz as hb

SIZE = 64.0   # px; paths are in px at this font size, baseline at y = 0
TRACK = -0.035  # em
TEXT = 'arelysig'
SPLIT = 5  # "arely" is ink, "sig" accent
OUT = 'src/ui/logoWordmark.ts'
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
DEFAULT_SOURCE = os.path.join(ROOT, "design/fonts/Archivo[wdth,wght].ttf")

font = instantiateVariableFont(
    TTFont(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SOURCE), {'wdth': 88, 'wght': 700}
)
upem = font['head'].unitsPerEm
scale = SIZE / upem
glyphset = font.getGlyphSet()
order = font.getGlyphOrder()

import io
buf_ttf = io.BytesIO(); font.save(buf_ttf)
face = hb.Face(hb.Blob(buf_ttf.getvalue())); hbfont = hb.Font(face)
buf = hb.Buffer(); buf.add_str(TEXT); buf.guess_segment_properties()
hb.shape(hbfont, buf, {'kern': True, 'liga': True})

x = 0.0
paths = {'ink': [], 'accent': []}
for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
    pen = SVGPathPen(glyphset, ntos=lambda v: f'{v:.2f}')
    tpen = TransformPen(pen, (scale, 0, 0, -scale, (x + pos.x_offset) * scale, -pos.y_offset * scale))
    glyphset[order[info.codepoint]].draw(tpen)
    paths['ink' if info.cluster < SPLIT else 'accent'].append(pen.getCommands())
    x += pos.x_advance + TRACK * upem
width = (x - TRACK * upem) * scale
hhea = font['hhea']

with open(OUT, 'w') as f:
    f.write('// Generated by scripts/make-wordmark.py — do not edit by hand.\n')
    f.write(f'// "{TEXT}" in Archivo Bold (wdth 88), letter-spacing {TRACK}em, outlined at\n')
    f.write(f'// {SIZE:g}px with the baseline at y = 0.\n\n')
    f.write('export const WORDMARK_SIZE = %g;\n' % SIZE)
    f.write('export const WORDMARK_WIDTH = %.2f;\n' % width)
    f.write('export const WORDMARK_ASCENT = %.2f;\n' % (hhea.ascent * scale))
    f.write('export const WORDMARK_DESCENT = %.2f;\n' % (-hhea.descent * scale))
    f.write("export const WORDMARK_INK = '%s';\n" % ' '.join(paths['ink']))
    f.write("export const WORDMARK_ACCENT = '%s';\n" % ' '.join(paths['accent']))
print(f'wrote {OUT}: width {width:.2f}px')
